"""add quantity to material asset

Revision ID: 0ef793d1eb4a
Revises: 9b3851709ff6
Create Date: 2025-05-30 17:36:32.161880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ef793d1eb4a'
down_revision = '9b3851709ff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_asset', schema=None) as batch_op:
        op.add_column('material_asset', sa.Column('quantity', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material_asset', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
