"""add meta_tag table

Revision ID: 1b25bf10e288
Revises: 3060e625ef5c
Create Date: 2025-06-02 09:47:19.494040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b25bf10e288'
down_revision = '3060e625ef5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meta_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('keywords', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meta_tag')
    # ### end Alembic commands ###
