"""add fields Open Graph і Twitter Cards

Revision ID: 21f62929a4a9
Revises: 4c5e20ddc396
Create Date: 2025-06-02 13:53:38.594157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f62929a4a9'
down_revision = '4c5e20ddc396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('og_title', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('og_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('og_image', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('twitter_title', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('twitter_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('twitter_image', sa.String(length=256), nullable=True))

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('meta_tag', schema=None) as batch_op:
        batch_op.drop_column('twitter_image')
        batch_op.drop_column('twitter_description')
        batch_op.drop_column('twitter_title')
        batch_op.drop_column('og_image')
        batch_op.drop_column('og_description')
        batch_op.drop_column('og_title')

    # ### end Alembic commands ###
