"""create news table

Revision ID: 30954ee40281
Revises: 37a6c2e002cd
Create Date: 2025-05-28 09:24:42.515415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30954ee40281'
down_revision = '37a6c2e002cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('news')
    # ### end Alembic commands ###
