"""add promotion_id to service

Revision ID: 37a6c2e002cd
Revises: b4638b7e3267
Create Date: 2025-05-28 07:35:54.801096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a6c2e002cd'
down_revision = 'b4638b7e3267'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotion_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_service_promotion_id',  # <-- constraint name
            'promotions',
            ['promotion_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('promotion_id')

    # ### end Alembic commands ###
