"""add Employee table

Revision ID: 3d2dc8d25513
Revises: 457f011f41ac
Create Date: 2025-05-31 08:48:46.752670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2dc8d25513'
down_revision = '457f011f41ac'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('employee',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=64), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_order_employee_id', 'employee', ['employee_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_employee_id', type_='foreignkey')
        batch_op.drop_column('employee_id')
        batch_op.drop_column('status')

    op.drop_table('employee')
    # ### end Alembic commands ###
