"""add order table

Revision ID: 457f011f41ac
Revises: 0ef793d1eb4a
Create Date: 2025-05-31 07:56:12.110042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457f011f41ac'
down_revision = '0ef793d1eb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('desired_date', sa.String(length=32), nullable=True),
    sa.Column('delivery_date', sa.String(length=32), nullable=True),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('year', sa.String(length=8), nullable=True),
    sa.Column('vin', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('repair', sa.String(length=128), nullable=True),
    sa.Column('parts', sa.String(length=128), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
