"""add meta_tag field schema_org

Revision ID: 4dcda696b894
Revises: 1b25bf10e288
Create Date: 2025-06-02 10:02:29.624248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcda696b894'
down_revision = '1b25bf10e288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schema_org', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meta_tag', schema=None) as batch_op:
        batch_op.drop_column('schema_org')

    # ### end Alembic commands ###
