"""add robot_txt table

Revision ID: 7fd2f67a38b9
Revises: fc62c9adeab5
Create Date: 2025-06-02 11:02:59.293094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fd2f67a38b9'
down_revision = 'fc62c9adeab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('robots_txt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('robots_txt')
    # ### end Alembic commands ###
