"""change promotion fields

Revision ID: b4638b7e3267
Revises: 892fdc531119
Create Date: 2025-05-27 20:53:59.431785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4638b7e3267'
down_revision = '892fdc531119'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.drop_column('price_to')
        batch_op.drop_column('price_from')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_from', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('price_to', sa.FLOAT(), nullable=True))
        batch_op.drop_column('end_date')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
