"""add sitemap table

Revision ID: fc62c9adeab5
Revises: 4dcda696b894
Create Date: 2025-06-02 10:42:38.515038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc62c9adeab5'
down_revision = '4dcda696b894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sitemap_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('lastmod', sa.String(length=32), nullable=True),
    sa.Column('changefreq', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitemap_page')
    # ### end Alembic commands ###
